# 定义几个流程（job），这里是定义了三个自动化流程
stages:
  - build
  - test
  - deploy

package:
  stage: test
  tags:
    - maven
  script:
    - docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn verify