# 脚本执行之后删除该镜像（为了不与下次镜像打包冲突）
after_script:
  - docker rmi $( docker images -q -f dangling=true)

# 定义几个流程（job），这里是定义了三个自动化流程
stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  tags:
    - maven
  script:
    - mvn clean install

job_test:
  stage: test
  tags:
    - maven
  script:
    - mvn test

job_deploy:
  stage: deploy
  tags:
    - maven
  script:
    # 通过Dockerfile生成镜像
    - mvn package docker:build
    # 删除已经在运行的容器
    - if [ $(docker ps -aq --filter name=demo) ]; then docker rm -f demo;fi
    # 通过镜像启动容器，并把本机端口映射到容器端口
    - docker run -d -p 8086:8086 --name demo xin-demo
  only:
    - master