image: maven:latest
# 脚本执行之后删除该镜像（为了不与下次镜像打包冲突）
after_script:
  - docker rmi $( docker images -q -f dangling=true)
cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

# 定义几个流程（job），这里是定义了三个自动化流程
stages:
  - build
  - test
  - deploy

package:
  stage: test
  tags:
    - maven
  script:
    - mvn verify