cache:
  key: maven-repository-cache
  paths:
    - /usr/local/maven/repo
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/usr/local/maven/repo"
# 本次构建的阶段：build package
stages:
- build
- package
# 构建 Job
build:
  stage: build
  tags:
  - maven
  script:
  - echo "=============== 开始编译构建任务 ==============="
  - mvn compile
# 打包
package:
  stage: package
  tags:
  - maven
  script:
  - echo "=============== 开始打包任务  ==============="
  - mvn package -Dmaven.test.skip=true