cache:
  key: maven-repository-cache
  paths:
    - /usr/local/maven/repo
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/usr/local/maven/repo"
# 本次构建的阶段：build package
stages:
  - compile
  - package
  - dock
# 构建 Job
build:
  stage: compile
  tags:
    - maven
  script:
    - echo "=============== 开始编译构建任务 ==============="
    - mvn compile
# 打包
package:
  stage: package
  tags:
    - maven
  script:
    - echo "=============== 开始打包任务  ==============="
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar

dock:
  stage: dock
  tags:
    - maven
  script:
    - docker build -t xin-demo  .
    - if [ $(docker ps -aq --filter name=demo) ]; then docker rm -f demo;fi
    - docker run -d -p 8086:8086 --link=mysqldx:mysql --name demo xin-demo
