cache:
  key: maven-repository-cache
  paths:
    - /usr/local/maven/repo
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/usr/local/maven/repo"
# 本次构建的阶段：build package
stages:
- dock

dock:
  stage: dock
  tags:
  - maven
  script:
  - docker build -t xin-demo  .
