# 脚本执行之后删除该镜像（为了不与下次镜像打包冲突）
after_script:
  - docker rmi $( docker images -q -f dangling=true)

# 定义几个流程（job），这里是定义了三个自动化流程
stages:
  - build
  - package
  - deploy
cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"


package:
  stage: package
  tags:
    - maven
  script:
    - echo "=============== 开始打包任务  ==============="
    - mvn package -Dmaven.test.skip=true

job_deploy:
  stage: deploy
  tags:
    - maven
  script:
    # 通过Dockerfile生成镜像
    - docker built -t xin-demo .
    # 删除已经在运行的容器
    - if [ $(docker ps -aq --filter name=demo) ]; then docker rm -f demo;fi
    # 通过镜像启动容器，并把本机端口映射到容器端口
    - docker run -d -p 8086:8086 --link=myseldx:mysql --name demo xin-demo
  only:
    - master